name: Johnny and Jarvis
favicon: null
layout_spectrum: 0.5230723202694207
typography_spectrum: 0.10236920206807554
title: 'Johnny Gets to Meet the Real "Lone Granger"'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ff0000'
    - '#000000'
    - '#ffffff'
    - '#00ffff'
    - '#a88d00'
  brandStrength: 0.0625
  lightness: 0.27892283047549427
  saturation: 0.01583632198162377
  rhythmicContrast: 0.3719978746958077
purpose: []
