name: Jarvis and Johnny
favicon: null
layout_spectrum: 0.7481
typography_spectrum: 0.15284
title: Jarvis and Johnny
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ff0000'
    - '#000000'
    - '#ffffff'
    - '#00ffff'
    - '#a88d00'
  brandStrength: 0
  lightness: 0.6875
  saturation: 0.5625
  rhythmicContrast: 0.75
purpose: []
